
spring:
  profiles:
    group:
      "local": "local, common"
      "dev": "dev, common"
      "prd": "prd, common"

---

spring:
  config:
    activate:
      on-profile: "common"
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
  jpa:
    open-in-view: false
    properties:
      hibernate.default_batch_fetch_size: 1000

jwt:
  secret: thisIsASecretKeyUsedForJwtTokenGenerationAndItIsLongEnoughToMeetTheRequirementOf256Bits
  access-token-expire-time: 600000
  refresh-token-expire-time: 15552000000

admin:
  super-user:
    id: ${SUPER_USER_ID:yjchoi}
    password: ${SUPER_USER_PASSWORD:12345678}

google:
  search-console:
    site-url: https://ztlog.io

github:
  url: https://api.github.com/graphql
  token: ${GITHUB_TOKEN:}
  user:
    name: ztlog-project
    comment-repo: ztlog-comment

# AWS S3 설정
aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:}
  s3:
    bucket: ztlog-s3-bucket
  region:
    static: ap-northeast-2
  stack:
    auto: false

# local, dev, prod 공통 설정
server:
  port: 8089
  servlet:
    context-path: '/admin'
    session:
      timeout: 60m
      cookie:
        http-only: true
        secure: false # local 개발 환경이므로 false, 운영 환경에서는 true 권장
        name: ZTLOG_SESSION_ID

springdoc:
  packages-to-scan: com.devlog.admin.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
#  mapper-locations: classpath:mybatis/mapper/**/**.xml
  mapper-locations: classpath:mapper/**/**.xml
  type-aliases-package: com.devlog.admin.service.**.dto.**


---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ztlog?useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  mvc:
    async:
      request-timeout: 2000
  thymeleaf:
    cache: false
  jpa:
    database: mysql
    generate-ddl: false
    show-sql: true # 콘솔에 SQL 출력
    properties:
      hibernate:
        format_sql: true # SQL을 예쁘게 포맷팅
        highlight_sql: true # SQL 키워드에 색상 부여 (지원 터미널일 경우)
        use_sql_comments: true # 쿼리에 주석 포함

logging:
  level:
    org.hibernate.SQL: debug # SQL 로그 레벨 설정
#    org.hibernate.orm.jdbc.bind: trace # (Spring Boot 3 기준) SQL 파라미터 바인딩 값 확인


---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/ztlog_dev?useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: Cy07351258!
  mvc:
    async:
      request-timeout: 2000
  thymeleaf:
    cache: false
  jpa:
    database: mysql
    generate-ddl: false
    show-sql: true # 콘솔에 SQL 출력
    properties:
      hibernate:
        format_sql: true # SQL을 예쁘게 포맷팅
        highlight_sql: true # SQL 키워드에 색상 부여 (지원 터미널일 경우)
        use_sql_comments: true # 쿼리에 주석 포함

logging:
  level:
    org.hibernate.SQL: debug # SQL 로그 레벨 설정
#    org.hibernate.orm.jdbc.bind: trace # (Spring Boot 3 기준) SQL 파라미터 바인딩 값 확인


---

spring:
  config:
    activate:
      on-profile: prd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/ztlog_prd?useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: Cy07351258!
  mvc:
    async:
      request-timeout: 2000
  thymeleaf:
    cache: false
  jpa:
    database: mysql
    generate-ddl: false
    #    show-sql: true